source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'

target 'Rudder-Braze_Example' do
  pod 'Rudder-Braze', :path => '../'
  pod 'BrazeUI' # Used to enable Braze IAM (In-App Message)
end
