use_frameworks!

platform :ios, '9.0'

target 'Rudder-Braze_Example' do
  pod 'Rudder-Braze', :path => '../'

  target 'Rudder-Braze_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
